### ISSUE TITLE
Question Regarding your Resume Parser

### ISSUE THREAD

**Issue by MikeDoes** [Vismayak/Resume_Parser_pdfs#1]
It seems to be the best one I could find online.

Majorlist.csv does not seem to exist.

Also, does "Omkar Pathak" that you gave credit to have a repository?

Awesome stuff! Thanks for sharing

**Comment by Vismayak** [comment]
Hi, Thank you for letting me know. I have just added the file and here is the link for Omkar Pathak's website.
https://www.omkarpathak.in/2018/12/18/writing-your-own-resume-parser/
